id: I05A2FC60
legacy_id: P000582
ocr_import_info:
  bdrc_scan_id: W1648
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T14:32:57'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T14:53:46.166338+00:00'
last_modified: 2022-08-30 22:55:04.408009
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1648
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1648
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དགོངས་གཅིག་ཡིག་ཆ།
  author: སྤྱན་སྔ་ཤེས་རབ་འབྱུང་གནས།
statistics:
  ocr_word_mean_confidence_index: 0.8230211099931428
  ocr_word_median_confidence_index: 0.8899999856948853
quality: null
bases:
  I00JW501143:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00JW501143
      total_pages: 670
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I00JW501143.txt
    statistics:
      ocr_word_median_confidence_index: 0.8899999856948853
      ocr_word_mean_confidence_index: 0.82362916515425
    legacy_id: v002
  I00JW501142:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00JW501142
      total_pages: 560
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I00JW501142.txt
    statistics:
      ocr_word_median_confidence_index: 0.8899999856948853
      ocr_word_mean_confidence_index: 0.8222793118625992
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
