id: I05A2FC60
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T14:37:33+00:00'
last_modified: '2022-06-07T12:22:50.353663+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1648
  title: དགོངས་གཅིག་ཡིག་ཆ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    8F01:
      image_group_id: I00JW501142
      title: Volume 1 of dgongs gcig yig cha dgons gcig yig cha detailed presentations
        of'bri-gun 'jig-rten-mgon-po'i dgons gcig precepts of mahayana buddhist philosophy
      total_pages: 560
      order: 1
      base_file: 8F01.txt
    87BF:
      image_group_id: I00JW501143
      title: Volume 2 of dgongs gcig yig cha dgons gcig yig cha detailed presentations
        of'bri-gun 'jig-rten-mgon-po'i dgons gcig precepts of mahayana buddhist philosophy
      total_pages: 670
      order: 2
      base_file: 87BF.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
